# Generated by Django 5.0.6 on 2024-07-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('discription', models.CharField(max_length=300)),
                ('c_images', models.ImageField(default='default_image.jpg', upload_to='category')),
            ],
        ),
    ]
