# Generated by Django 5.0.6 on 2024-07-29 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest1', '0002_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='c_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest1.category'),
        ),
    ]
