# Generated by Django 5.0.6 on 2024-07-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest1', '0006_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('no_guest', models.IntegerField()),
            ],
        ),
    ]
