# Generated by Django 5.0.6 on 2024-07-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest1', '0007_reservedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedetails',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
