# Generated by Django 5.0.6 on 2024-07-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest1', '0008_alter_reservedetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedetails',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservedetails',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
